#+title: Harry's Doom Emacs Config
#+author: Harry Tucker

# HTML and LaTeX export --------------------------------------------------------
#+options: toc:nil
#+latex_class: mimore
# ------------------------------------------------------------------------------

* About
This is a literate Doom Emacs configuration that tangles into the various
configuration files that Doom expects. The configuration is split into modular
files for better organization:

| Module           | Purpose                                         |
|------------------+-------------------------------------------------|
| =ui.org=           | Theme, fonts, modeline, and visual settings     |
| =editor.org=       | Evil mode, projectile, and completion settings  |
| =shell.org=        | Eshell and terminal emulator configuration      |
| =programming.org=  | Language-specific settings (Go, Rust, Python)   |
| =writing.org=      | Org mode, Org Roam, Markdown, and LaTeX export  |
| =tools.org=        | Kubernetes, AI assistants (gptel, ECA)          |
| =workarounds.org=  | MacOS-specific fixes and quirks                 |

First, enable lexical binding for better performance:
#+begin_src elisp
;;; -*- lexical-binding: t; -*-
#+end_src

** Build Information
Running on Emacs 30.1 with native compilation on Apple Silicon:
#+begin_src elisp :tangle no
(emacs-version)
#+end_src

#+RESULTS:
: GNU Emacs 30.1 (build 2, aarch64-apple-darwin24.3.0, NS appkit-2575.40 Version 15.3.1 (Build 24D70))
:  of 2025-03-07

* Configuration
** User Identification
Set the name and email address used by Emacs for things like email composition
and source control metadata.
#+begin_src elisp
(setq user-full-name "Harry Tucker"
      user-mail-address "tucker.harry@outlook.com")
#+END_SRC

** Load Modules
Load configuration from separate module files. Each module is a literate Org
file that tangles into elisp, which =org-babel-load-file= handles automatically.
#+begin_src elisp
(org-babel-load-file (expand-file-name "modules/ui.org" doom-user-dir))
(org-babel-load-file (expand-file-name "modules/editor.org" doom-user-dir))
(org-babel-load-file (expand-file-name "modules/shell.org" doom-user-dir))
(org-babel-load-file (expand-file-name "modules/programming.org" doom-user-dir))
(org-babel-load-file (expand-file-name "modules/writing.org" doom-user-dir))
(org-babel-load-file (expand-file-name "modules/tools.org" doom-user-dir))
(org-babel-load-file (expand-file-name "modules/workarounds.org" doom-user-dir))
#+end_src

* Packages
Additional packages from [[https://melpa.org][MELPA]] that aren't exposed through Doom's =init.el=,
imported using the =package!= macro. Organized by category.
#+begin_src elisp :tangle packages.el
;; -*- no-byte-compile: t; -*-
;;; .doom.d/packages.el

;; Testing - BDD support
(package! feature-mode)

;; Python - docstring editing and syntax highlighting
(package! python-docstring)

;; Protobuf/gRPC - .proto file support
(package! protobuf-mode)

;; Caddy - Caddyfile syntax support
(package! caddyfile-mode)

;; Kubernetes - cluster management and Jsonnet config files
(package! kubernetes)
;;(package! kele) ; temporarily disabled (see modules/tools.org)
(package! jsonnet-mode)

;; Org Mode extensions
(unpin! org-roam)      ; use latest org-roam
(package! org-roam-ui) ; graph visualization web UI
(package! engrave-faces) ; better syntax highlighting in LaTeX exports

;; PostgreSQL - database browser and client library
(package! pg :recipe (:host github :repo "emarsden/pg-el"))
(package! pgmacs :recipe (:host github :repo "emarsden/pgmacs"))

;; AI Assistants
(unpin! gptel) ; use latest gptel
(package! macher :recipe (:host github :repo "kmontag/macher"))
(package! eca :recipe (:host github :repo "editor-code-assistant/eca-emacs" :files ("*.el")))
(package! shell-maker)
(package! acp)
(package! agent-shell)

;; Utilities
(package! command-log-mode) ; display keystrokes in a buffer
(package! prism)            ; scope-based syntax highlighting
(package! flyover)          ; modern flycheck display
(package! eat)              ; terminal emulator for eshell
#+end_src

